

[[redirects]]
  from = "/api/*"
  to = "https://newsapibackend-746u.onrender.com/api/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"